import type { Project, TechPill } from "./types";

export const techPills: TechPill[] = [
  { label: "Claude AI" },
  { label: "Antigravity IDE" },
  { label: "React" },
  { label: "JavaScript" },
  { label: "Python" },
  { label: "HTML" },
  { label: "CSS" },
  { label: "Vercel" },
  { label: "Supabase" },
  { label: "Maya" },
  { label: "Adobe Suite" },
];

export const projects: Project[] = [
  {
    id: "primovera",
    title: "Primovera",
    description: "Full-stack build for a Philippine-based construction firm — branded, performant, and mobile-first.",
    category: "web",
    image: "/images/Primovera.webp",
    imageAlt: "Primovera construction firm website screenshot",
    link: "https://primovera.net/",
  },
  {
    id: "dragonflyy",
    title: "Dragonflyy Studio",
    description: "Boutique lash studio in Orange County — elegant booking-ready site with custom brand identity.",
    category: "web",
    image: "/images/LashDesk.webp",
    imageAlt: "Dragonflyy Studio lash salon website screenshot",
    link: "https://dragonflyybar.com/",
  },
  {
    id: "sintabymarie",
    title: "SintaByMarie",
    description: "Handcrafted jewelry e-commerce store with full product catalog and checkout flow.",
    category: "web",
    image: "/images/SintaByMarie.webp",
    imageAlt: "SintaByMarie jewelry e-commerce site screenshot",
    link: "http://sintabymariejewelry.com/",
  },
  {
    id: "lg-athletics",
    title: "LG Athletic Performance",
    description: "Youth athletic training facility in Huntington Beach — clean, conversion-focused landing page.",
    category: "web",
    image: "/images/LGathletics.png",
    imageAlt: "LG Athletic Performance training facility website screenshot",
    link: "https://lgathleticperformance.com/",
  },
  {
    id: "mystery-entertainment",
    title: "Mystery Entertainment",
    description: "LA entertainment label site — bold visual identity and artist-focused layout.",
    category: "web",
    image: "/images/MysteryEntertainment.png",
    imageAlt: "Mystery Entertainment LA music label website screenshot",
    link: "https://mystery-co.vercel.app/",
  },
  {
    id: "marias-kusina",
    title: "Maria's Kusina",
    description: "Filipino panciteria in Buena Park, est. 1995 — heritage brand with warm digital presence.",
    category: "web",
    image: "/images/marias-kusina.png",
    imageAlt: "Maria's Kusina Filipino restaurant website screenshot",
    link: "https://ajsamudio.github.io/MariasKusina/",
  },
  {
    id: "whipple-taqueria",
    title: "Whipple Taqueria",
    description: "High-rated taqueria in Union City — vibrant, food-forward site built to drive foot traffic.",
    category: "web",
    image: "/images/WhippleTacos.png",
    imageAlt: "Whipple Taqueria restaurant website screenshot",
    link: "https://ajsamudio.github.io/WhippleTaqueria/",
  },
  {
    id: "wall-writers",
    title: "Wall Writers Coffee",
    description: "Upscale coffee shop in Irvine — minimal, aesthetic-first site with a strong brand voice.",
    category: "web",
    image: "/images/Wallwriters.png",
    imageAlt: "Wall Writers Coffee shop website screenshot",
    link: "https://ajsamudio.github.io/WallWriters/",
  },
  {
    id: "self-finance",
    title: "Self Finance",
    description: "Personal finance SaaS — Google auth, dashboard UI, and budgeting logic built from scratch.",
    category: "web",
    image: "/images/FinanceTracker.png",
    imageAlt: "Self Finance personal finance SaaS app screenshot",
    link: "https://self-finance-beryl.vercel.app/",
  },
  {
    id: "vinyl-3d",
    title: "Vinyl 3D",
    description: "Scroll-driven 3D vinyl record experience — interactive Three.js animation in the browser.",
    category: "web",
    image: "/images/3dVinyl.png",
    imageAlt: "3D vinyl record interactive web experience screenshot",
    link: "https://ajsamudio.github.io/3dVinyl/",
  },
  {
    id: "neurospark",
    title: "NeuroSpark",
    description: "AI-powered productivity suite — task management with smart suggestions and clean UX.",
    category: "web",
    image: "/images/NeuroSpark.webp",
    imageAlt: "NeuroSpark AI productivity suite screenshot",
    link: "https://ajsamudio.github.io/playground/NeuroSparkProductivity.html",
  },
  {
    id: "blackjack",
    title: "BlackJack",
    description: "Classic browser-based BlackJack game built with vanilla JavaScript — fast and fun.",
    category: "web",
    image: "/images/blackJack.webp",
    imageAlt: "BlackJack browser card game screenshot",
    link: "https://ajsamudio.github.io/playground/BlackJack.html",
  },
  {
    id: "diceroll",
    title: "DiceRoll",
    description: "Animated dice roller web app with smooth physics-inspired transitions.",
    category: "web",
    image: "/images/diceRoll.webp",
    imageAlt: "DiceRoll animated dice roller web app screenshot",
    link: "https://ajsamudio.github.io/playground/diceRoll.html",
  },
  {
    id: "community-initiative",
    title: "Community Initiative",
    description: "Visual identity and poster series for a local community outreach program.",
    category: "design",
    image: "/images/pos1upd.webp",
    imageAlt: "Community Initiative poster and visual identity design",
    link: "#",
  },
  {
    id: "3d-environment",
    title: "3D Environment",
    description: "Sci-fi space environment modeled and rendered in Autodesk Maya.",
    category: "design",
    image: "/images/Capture3.webp",
    imageAlt: "3D sci-fi space environment rendered in Maya",
    link: "#",
  },
  {
    id: "service-campaign",
    title: "Service Campaign",
    description: "Print and digital materials for a community service campaign — cohesive visual system.",
    category: "design",
    image: "/images/post2upd.webp",
    imageAlt: "Service campaign print and digital design materials",
    link: "#",
  },
  {
    id: "fortnite-montage",
    title: "Fortnite Montage",
    description: "High-energy gaming montage edit with dynamic cuts, motion graphics, and sound design.",
    category: "video",
    image: "/images/Fvideo.webp",
    imageAlt: "Fortnite gaming montage video thumbnail",
    link: "#",
    videoSrc: "/images/Fnite.mp4",
    videoPoster: "/images/Fvideo.webp",
  },
  {
    id: "dodger-edit",
    title: "Dodger Edit",
    description: "World Series highlight reel for the LA Dodgers — cinematic pacing with broadcast-style graphics.",
    category: "video",
    image: "/images/Dvideo.webp",
    imageAlt: "LA Dodgers World Series highlight reel thumbnail",
    link: "#",
    videoPoster: "/images/Dvideo.webp",
  },
];
